# Generated by Django 5.2.15 on 2026-06-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='years_experience',
        ),
    ]
